spring:
  datasource:
    url: jdbc:mysql://localhost:3306/core_security?serverTimezone=Asia/Seoul&chracterEncoding=utf-8
    username: root
    password: mysql

#  datasource:
#    url: jdbc:h2:mem:security
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
    add-properties: true